name = "TIKI Product Discount"
type = "product_discounts"
api_version = "2022-07"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/discount/product"
details = "/discount/product/:id"

[input.variables]
namespace = "$app:mytiki"
key = "collections"
